# https://lefthook.dev/configuration/index.html
# TODO(@s0cks): add
# commit-msg:
#   commands:
#     "lint commit message":
#       run: cog verify --file {1}
pre-commit:
  commands:
    "detect secrets":
      files: git diff --name-only --diff-filter=d --staged
      run: gitleaks protect --no-banner --staged --redact --verbose
